### ISSUE TITLE
Some problems appear in the code.

### ISSUE THREAD

**Issue by GitttttBottttt** [srozb/parasite#1]
![image](https://user-images.githubusercontent.com/36138300/143866988-4c109b58-bde9-4581-8aa9-f69ef87939df.png)

**Comment by srozb** [comment]
did you try to compile sources with `nimble build` command? could you provide output from `nimble list --ver -i` ?

what's the nim compiler version by the way?

**Comment by GitttttBottttt** [comment]
> did you try to compile sources with `nimble build` command? could you provide output from `nimble list --ver -i` ?
> 
> what's the nim compiler version by the way?

![image](https://user-images.githubusercontent.com/36138300/143973434-62343f0e-e696-47b1-b67e-4c41f9a1459f.png)

**Comment by srozb** [comment]
This is weird as I don't have such issues with very similar environment, but I've spotted a bug and improved couple of things so you might wanna try tag [v.0.1.1](https://github.com/srozb/parasite/tree/v.0.1.1).

There is also already compiled release for your architecture if you want to play with this project.

Let me know if v.0.1.1 solve your compilation issue.

**Comment by srozb** [comment]
Closing as the issue is clearly stalled. Feel free to reopen.
