### ISSUE TITLE
Support for x86.

### ISSUE THREAD

**Issue by Kesanov** [srozb/parasite#2]
Hello, I was playing with the idea of using Nim for modding old game binary.

However, it is in the 32bit format, which your method does not support.
Would you share some insight on how to set things up?

**Comment by srozb** [comment]
Hi,
You have 2 options to build the 32bit version of this project:

1. Install the 32 bit version of Nim and run finish.exe to download and extract corresponding 32bit version of mingw
2. Just download the [mingw-32](https://nim-lang.org/download/mingw32.7z), extract and put within your environment `%PATH%`. Then compile like this: 

```
cd src
nim --cpu:i386 -d:release c parasite.nim
```

I was able to build 32 bit version but haven't tested yet. 

Please let me know what's the outcome so I can enrich the readme.

You may find some more information [here](https://www.mail-archive.com/nim-general@lists.nim-lang.org/msg06008.html).

**Comment by Kesanov** [comment]
So I have looked a little bit into it and the old binary has been compiled with the old VS2002 (vcc 7.0).
It uses no stdlib and dynamically links against msvcr71.dll. 
I have been told, that if I use CRT functions like malloc  that come from different msvcr, I will cause a memory corruption.
Is that correct?

So now I need to either patch the old binary to use newer CRT functions, or patch the Nim binary to use the old CRT functions.

**Comment by srozb** [comment]
I don't have such a deep understanding of compiler internals / memory management to help you out with this but I'm sure you could ask around on nim's forum or discord where ppl are very eager to help and for sure will understand this topic very well.
I will close this thread for now but feel free to reopen or contact me directly in case you have any further questions related to this project. I'll be happy to help.
